apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    maintainer: sudhanshu
    env: prod
    team: gfg
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80